### ISSUE TITLE
consul::install_binary should not install compilers on host

### ISSUE THREAD

**Issue by dpkp** [johnbellone/consul-cookbook#169] opened 2015-05-05 19:52 UTC
I'd like to avoid installing compilers and other build tools on production servers. But the ::install_binary recipe causes compilers and other tools to get installed via apt (testing on ubuntu 12.04). It looks like this is caused by the libarchive cookbook dependency, which compiles the libarchive library as part of the ruby gem install. Due to the compiler install, I can't use the cookbook to install consul on production servers...

```
> kitchen converge default-ubuntu-1204
...
       Recipe: build-essential::_debian
         * apt_package[autoconf] action install
           - install version 2.68-1ubuntu2 of package autoconf
         * apt_package[binutils-doc] action install
           - install version 2.22-6ubuntu1.3 of package binutils-doc
         * apt_package[bison] action install
           - install version 1:2.5.dfsg-2.1 of package bison
         * apt_package[build-essential] action install (up to date)
         * apt_package[flex] action install
           - install version 2.5.35-10ubuntu3 of package flex
         * apt_package[gettext] action install
           - install version 0.18.1.1-5ubuntu3 of package gettext
         * apt_package[ncurses-dev] action install
           - install version (none) of package ncurses-dev
...
```

**Comment by rsteube** [comment] 2015-05-06 09:23
+1
[ark](https://supermarket.chef.io/cookbooks/ark) might be an alternative

**Comment by rsteube** [comment] 2015-05-06 10:54
Here's an example for `install_binary.rb`, which includes download, extraction and symbolic link (but with different folder structure in opt):
```ruby
include_recipe 'ark'
ark 'consul' do
  url Chef::Consul.remote_url(node)
  version node['consul']['version']
  strip_components 0
  prefix_root '/opt'
  prefix_home '/opt'
  has_binaries ['consul/consul']
end
```
Simple extraction with current folder structure can be done like this:
```ruby
include_recipe 'ark'
ark 'consul' do
  url Chef::Consul.remote_url(node)
  path Chef::Consul.install_path(node)
  creates 'consul'
  action :cherry_pick
end
```

**Comment by ewr** [comment] 2015-05-14 15:03
:+1: to using something other than libarchive. I just discovered this morning that chef runs on several of my nodes have been broken for a while, but they were failing via libarchive during the compile phase and were therefore not far enough to have installed the handlers that would have alerted me.

**Comment by dpkp** [comment] 2015-05-14 15:26
ewr: I think that is worth opening a separate issue!

**Comment by johnbellone** [comment] 2015-05-24 13:38
I'll revisit this in the 1.0 release that's on the develop branch. Right now it is using libarchive but maybe @reset and I can figure a way out to not yank in build-essentials.

**Comment by johnbellone** [comment] 2015-06-16 11:18
This is a duplicate of #165.

**Comment by reset** [comment] 2015-06-16 17:52
@johnbellone the ark cookbook is a mess in it's own way. The libarchive lwrp is _actually_ idempotent but seems to be having issues on some machines. We can triage those issues or come up with a pure ruby way to get the same behaviour that libarchive is giving us.

**Comment by ewr** [comment] 2015-06-16 18:14
It doesn't look like they've followed through on pushing it to Supermarket, but this Ooyala tarball cookbook is an attempt to handle unarchiving via just built-in Ruby bits:

https://github.com/ooyala/tarball-chef-cookbook
http://engineering.ooyala.com/blog/stop-bashing-tarballs-chef

**Comment by reset** [comment] 2015-06-16 18:21
@ewr they're on the right track with the pure Ruby approach but unfortunately it's only for tarballs :frowning:. Libarchive (the c library) identifies what compression mechanism was used and then rolls with it. That, portability, and idempotency are the keys that we need.

**Comment by ewr** [comment] 2015-06-16 18:24
I was going to say "yeah, but the Consul binaries are just tarballs", but they aren't: they're zip files.

So, carry on...

**Comment by johnbellone** [comment] 2015-06-16 19:19
@reset Yeah we spoke about ark cookbook last time. I am wondering if we can get by using [ffi-libarchive](https://bitbucket.org/lyro/ffi-libarchive) - does that still need development headers?

**Comment by johnbellone** [comment] 2015-07-01 02:39
I have a test branch locally and I'll see if I can wire in ffi-libarchive. Any objects @reset?

**Comment by reset** [comment] 2015-07-01 18:08
@johnbellone not at all - just need to make sure it's actually idempotent. I do that in the libarchive cookbook by reading the contents of the archive and comparing to what is on disk before performing any extractions.

**Comment by johnbellone** [comment] 2015-07-22 01:59
I am closing this since @reset merged the above commit. This no longer requires build-essentials and merely requires libarchive.

**Closed by johnbellone** 2015-07-22 01:59 UTC
Labels: bug, question
